### ISSUE TITLE
C1218IOError('failed 3 times to correctly send a frame'

### ISSUE THREAD

**Issue by Nameth** [securestate/termineter#6]
We are using RS232 (serial cable) optical probe for our connection - http://probeformeters.com/brochure/brochure_kmk131_en.pdf

We are testing the Atlas EDMI MK10D Three Phase Electronic Meter - http://www.edmi-meters.co.uk/wp-content/uploads/2017/06/Mk10D_2017.pdf

We have installed the termineter app on our Linux box but we are facing some difficulties.
We receive the error **C1218IOError('failed 3 times to correctly send a frame')**
We have also tried this in Windows (with Python 3.6.3 installed) using a USB to serial convertor (with FTDI chip) and we get the same error.
We have also tried a serial to USB converter but it outputs the same error. 

We then emailed the optical probe supplier for help to which they replied:
1. It must be used with an ANSI meter.
2. You must make sure you give power to probe from pin4 or pin7 which means RTS enabled in windows application.

We meet the condition for number 1 but not sure about number 2. We imported the DTS(RTS) to python, perhaps not done correctly.

Can you point us in the right direction? 

Thanks

**Comment by zeroSteiner** [comment]
The default is to have `RTS` enabled and `DTR` disabled. These are set [here](https://github.com/securestate/termineter/blob/master/lib/c1218/connection.py#L100-L111).

If you start termineter with logging set to debugging, you'll be able to see frames being sent (and hopefully received). Can you try that and post the logs here? You can start it in debugging module by doing `./termineter -L DEBUG`.

**Comment by Nameth** [comment]
Thanks for your help. This is what I get:

termineter > set SERIAL_CONNECTION /dev/ttyS0
SERIAL_CONNECTION => /dev/ttyS0
termineter > connect
INFO     opening serial device: /dev/ttyS0
DEBUG    successfully opened serial device: /dev/ttyS0
DEBUG    applying pySerial settings dictionary
DEBUG    set RTS to True
DEBUG    set DTR to False
INFO     selective table caching has been enabled
DEBUG    sending frame,  length: 9   data: ee0000000001201310
ERROR    received empty response after writing data
ERROR    received empty response after writing data
ERROR    received empty response after writing data
CRITICAL failed 3 times to correctly send a frame
ERROR    serial connection has been opened but the meter is unresponsive
ERROR    Caught C1218IOError: 'failed 3 times to correctly send a frame'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/termineter/interface.py", line 193, in do_connect
    self.frmwk.test_serial_connection()
  File "/usr/lib/python3/dist-packages/termineter/core.py", line 401, in test_serial_connection
    self.serial_connect()
  File "/usr/lib/python3/dist-packages/termineter/core.py", line 359, in serial_connect
    raise error
  File "/usr/lib/python3/dist-packages/termineter/core.py", line 356, in serial_connect
    self.serial_connection.start()
  File "/usr/lib/python3/dist-packages/c1218/connection.py", line 271, in start
    self.send(C1218IdentRequest())
  File "/usr/lib/python3/dist-packages/c1218/connection.py", line 144, in send
    raise C1218IOError('failed 3 times to correctly send a frame')
c1218.errors.C1218IOError: 'failed 3 times to correctly send a frame'
[-] Caught C1218IOError: 'failed 3 times to correctly send a frame'

**Comment by zeroSteiner** [comment]
Well it's never receiving anything, not even the ACK that the frame was successfully sent. I would look at your serial settings and make sure the others like the baudrate etc are all configured correctly. Do you have any other software that's using this probe and meter combination?

**Comment by Nameth** [comment]
I do not have any other probs or meters, termineter was installed on a fresh KALI box. When we send the connect command, the device actually blinks three times. I will do a video and upload it on here.

**Comment by Nameth** [comment]
https://youtu.be/CyRDPOmNY-c

You can see it it blink three times.
If you change the speed of the video, you maybe able to see it better.

**Comment by zeroSteiner** [comment]
Have you been able to verify the serial settings for your particular probe? The light blinking doesn't necessarily mean that the settings are correct.

**Comment by Nameth** [comment]
stty -F /dev/ttyS0 115200

**Comment by zeroSteiner** [comment]
For that you're going to want to set them from within termineter using the advanced options.

```
termineter > show advanced

Advanced Framework Options
==========================

  Name               Value    Description
  -----------------  -------  --------------------------------------------
  AUTO_CONNECT       True     automatically handle connections for modules
  C1218_MAX_PACKETS  2        c12.18 maximum packets for reassembly
  C1218_PACKET_SIZE  512      c12.18 maximum packet size
  CACHE_TABLES       True     cache certain read-only tables
  SERIAL_BAUD_RATE   9600     serial connection baud rate
  SERIAL_BYTE_SIZE   8        serial connection byte size
  SERIAL_STOP_BITS   1        serial connection stop bits
  TABLE_FORMAT       simple   the format to print tables in

termineter > set SERIAL_BAUD_RATE 115200
SERIAL_BAUD_RATE => 115200
termineter > 
```

Notice that these are at the framework level, so you can't set them while a module is in use (those would be the module-specific options and advanced options.

**Comment by Scoo10** [comment]
good day, I have tried to connect with smart meter in Mexico of the
brand IUSA, but I get it, it fails. 'failed 3 times to correctly send
to frame. the probe I use is RS232 OPTICAL PROBE

KMK113 BROCHUREKMK133 BROCHURE
The probe has DB9 Male interface for RS232 connection and it also has
coiled cable so it can easily be used with handheld units with
suitable interface and / or data collector devices. to connect to
windows .The error is for the safety of the smart meter.. did yo have
to conect plase me contact.




2018-02-18 14:00 GMT-06:00 Nameth <notifications@github.com>:

**Comment by zeroSteiner** [comment]
@Scoo10 if you're having trouble, can you please open a separate issue? Thanks!

**Comment by Nameth** [comment]
I was unable to resolve this, i gave up in the end.
